# Dataset configuration for ball detection
path: .  # dataset root directory
train: train  # train images (relative to 'path')
val: valid  # val images (relative to 'path')
test: test  # test images (relative to 'path')

# Classes
names:
  0: ball

# Number of classes
nc: 1 